name = "DPB"
grammar = "dpb"
path_suffixes = ["dpb"]
line_comments = ["# "]
block_comment = ["<!-- ", " -->"]

[brackets]
"(" = ")"
"{" = "}"
"[" = "]"
"<" = ">"
"\"" = "\""

[auto_pairs]
"(" = ")"
"{" = "}"
"[" = "]"
"\"" = "\""
